site_name: pl_helper_scripts
site_url: https://p-linux.github.io/pl_helper_scripts/
site_description: Some helper scripts useful for P-Linux.
site_author: peter1000
site_favicon: images/p_linux_favicon.ico

repo_url: https://github.com/P-Linux/pl_helper_scripts/

pages:
- Home: index.md
- User Guide:
    - How To: user_guide/00_how_to.md
- About:
    - Readme: about/readme.md
    - License: about/license.md
    - Release Notes: about/release-notes.md

markdown_extensions:
    - toc:
        permalink: 
    - admonition:

extra_css: [css/extra.css]

use_directory_urls: true
copyright: Copyright (c) 2016, <a href="https://github.com/peter1000"><strong>peter1000</strong></a>

theme: 'bootstrap'
